<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#A-first-look-at-a-neural-network" data-toc-modified-id="A-first-look-at-a-neural-network-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>A first look at a neural network</a></span></li></ul></div>

2.1　初识神经网络

In [2]:
!pip install keras 
#下载keras模块

In [1]:
import keras
keras.__version__

'2.4.3'

# A first look at a neural network

This notebook contains the code samples found in Chapter 2, Section 1 of [Deep Learning with Python](https://www.manning.com/books/deep-learning-with-python?a_aid=keras&a_bid=76564dff). Note that the original text features far more content, in particular further explanations and figures: in this notebook, you will only find source code and related comments.

----

We will now take a look at a first concrete example of a neural network, which makes use of the Python library Keras to learn to classify 
hand-written digits. Unless you already have experience with Keras or similar libraries, you will not understand everything about this 
first example right away. You probably haven't even installed Keras yet. Don't worry, that is perfectly fine. In the next chapter, we will 
review each element in our example and explain them in detail. So don't worry if some steps seem arbitrary or look like magic to you! 
We've got to start somewhere.

The problem we are trying to solve here is to classify grayscale images of handwritten digits (28 pixels by 28 pixels), into their 10 
categories (0 to 9). The dataset we will use is the MNIST dataset, a classic dataset in the machine learning community, which has been 
around for almost as long as the field itself and has been very intensively studied. It's a set of 60,000 training images, plus 10,000 test 
images, assembled by the National Institute of Standards and Technology (the NIST in MNIST) in the 1980s. You can think of "solving" MNIST 
as the "Hello World" of deep learning -- it's what you do to verify that your algorithms are working as expected. As you become a machine 
learning practitioner, you will see MNIST come up over and over again, in scientific papers, blog posts, and so on.

The MNIST dataset comes pre-loaded in Keras, in the form of a set of four Numpy arrays:

In [3]:
from keras.datasets import mnist

(train_images, train_labels), (test_images, test_labels) = mnist.load_data()

6w张 train_images#训练集 train_labels 标准答案
1w张 test_image 测试集 test_labels
train学习，test测试
train里加上val_image val_label参数不够好，调整参数
80%train,20%val(验证资料)


MNIST 手写字符数据集
训练集为 60,000 张 28x28 像素灰度图像，测试集为 10,000 同规格图像，总共 10 类数字标签。

https://keras.io/zh/datasets/ 数据集

`train_images` and `train_labels` form the "training set", the data that the model will learn from. The model will then be tested on the 
"test set", `test_images` and `test_labels`. Our images are encoded as Numpy arrays, and the labels are simply an array of digits, ranging 
from 0 to 9. There is a one-to-one correspondence between the images and the labels.

Let's have a look at the training data:

In [5]:
train_images.shape #3维量 每张图片28*28像素

(60000, 28, 28)

In [24]:
train_images[0]#康康图

array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.     

In [6]:
len(train_labels)#标准答案长度

60000

In [7]:
train_labels

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

Let's have a look at the test data:

In [8]:
test_images.shape

(10000, 28, 28)

In [9]:
len(test_labels)

10000

In [10]:
test_labels

array([7, 2, 1, ..., 4, 5, 6], dtype=uint8)

Our workflow will be as follow: first we will present our neural network with the training data, `train_images` and `train_labels`. The 
network will then learn to associate images and labels. Finally, we will ask the network to produce predictions for `test_images`, and we 
will verify if these predictions match the labels from `test_labels`.

Let's build our network -- again, remember that you aren't supposed to understand everything about this example just yet.

In [13]:
from keras import models
from keras import layers

network = models.Sequential() #一层层的神经网络用sequential，开始叠积木
network.add(layers.Dense(512, activation='relu', input_shape=(28 * 28,))) #隐藏层里512个神经元，28*28像素的
#转换成784*1，input里直接写（784，）也可以
network.add(layers.Dense(10, activation='softmax'))#output，0-9一共10个神经元
#activation：激活函数，relu:第二象限为0，第一象限是45°线
#softmax：（归一化指数函数）它能将一个含任意实数的K维向量z“压缩”到另一个K维实向量σ(z)中，使得每一个元素的范围都在(0,1)之间，并且所有元素的和为1。

输入层：784  隐藏层(784+1)* 512个参数需要估计 输出层:(512+1)* 10个参数需要估计
加1因为b1+w1x1+....+w784x784，那个b1

In [15]:
network.summary() #隐藏层(784+1)* 512=401920个参数， output层(512+1)* 10=5130个参数

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_4 (Dense)              (None, 512)               401920    
_________________________________________________________________
dense_5 (Dense)              (None, 10)                5130      
Total params: 407,050
Trainable params: 407,050
Non-trainable params: 0
_________________________________________________________________


input hidden output


The core building block of neural networks is the "layer", a data-processing module which you can conceive as a "filter" for data. Some 
data comes in, and comes out in a more useful form. Precisely, layers extract _representations_ out of the data fed into them -- hopefully 
representations that are more meaningful for the problem at hand. Most of deep learning really consists of chaining together simple layers 
which will implement a form of progressive "data distillation". A deep learning model is like a sieve for data processing, made of a 
succession of increasingly refined data filters -- the "layers".

Here our network consists of a sequence of two `Dense` layers, which are densely-connected (also called "fully-connected") neural layers. 
The second (and last) layer is a 10-way "softmax" layer, which means it will return an array of 10 probability scores (summing to 1). Each 
score will be the probability that the current digit image belongs to one of our 10 digit classes.

To make our network ready for training, we need to pick three more things, as part of "compilation" step:

* A loss function: the is how the network will be able to measure how good a job it is doing on its training data, and thus how it will be 
able to steer itself in the right direction.
* An optimizer: this is the mechanism through which the network will update itself based on the data it sees and its loss function.
* Metrics to monitor during training and testing. Here we will only care about accuracy (the fraction of the images that were correctly 
classified).

The exact purpose of the loss function and the optimizer will be made clear throughout the next two chapters.

densely-connected/neural layers上一层的所有output连接到下一层的input（全连接）
input层784个连接到隐藏层中第1个参数，第2个参数....第512个参数

训练网络

In [18]:
network.compile(optimizer='rmsprop',
                loss='categorical_crossentropy',
                metrics=['accuracy']) #optimizer选择优化器训练，最常用的是'rmsprop'和'Adam'
#loss损失函数，使用MSE效果不好，metrics：预测正确率

优化器：https://keras.io/zh/optimizers/#rmsprop 


Before training, we will preprocess our data by reshaping it into the shape that the network expects, and scaling it so that all values are in 
the `[0, 1]` interval. Previously, our training images for instance were stored in an array of shape `(60000, 28, 28)` of type `uint8` with 
values in the `[0, 255]` interval. We transform it into a `float32` array of shape `(60000, 28 * 28)` with values between 0 and 1.

preprocess预处理资料
28* 28像素，每个格子里0-255个深浅。深度学习一般使用数字小的输入。先标准化压缩到0-1之间
uint8：8位的整数

In [19]:
train_images = train_images.reshape((60000, 28 * 28)) #三维资料(60000,28,28)改变维度
train_images = train_images.astype('float32') / 255#整数改为浮点数/255

test_images = test_images.reshape((10000, 28 * 28))
test_images = test_images.astype('float32') / 255

We also need to categorically encode the labels, a step which we explain in chapter 3:

这里训练出来0-9是没有大小概念的，比如5就是[0,0,0,0,0,1,0,0,0,0]，这样写的好处就是当读取一个数字的时候，[...,1,000]每个格子都会有个概率，其中5所在的概率会特别大

In [20]:
from keras.utils import to_categorical

train_labels = to_categorical(train_labels) #训练资料放进去，to_categorical编码
test_labels = to_categorical(test_labels)

In [21]:
train_labels

array([[0., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.]], dtype=float32)

In [23]:
train_labels.shape#6w个样本，每个样本10个单位

(60000, 10)

We are now ready to train our network, which in Keras is done via a call to the `fit` method of the network: 
we "fit" the model to its training data.

In [26]:
network.fit(train_images, train_labels, epochs=5, batch_size=128) #.fit是开始估计参数
#6w张，不要扔那么多进去，每次扔128个进去，一般batch_size=2^x 
#每次扔128个，扔到6w个算一次，epochs=5是跑5次
#资料不错loss: 0.0363一直在下降，accuracy: 0.9889一直在上升，太高也不好，可能会有过失

Epoch 1/5
469/469 [==============================] - 2s 4ms/step - loss: 0.0278 - accuracy: 0.9917
Epoch 2/5
469/469 [==============================] - 2s 4ms/step - loss: 0.0210 - accuracy: 0.9937
Epoch 3/5
469/469 [==============================] - 2s 4ms/step - loss: 0.0166 - accuracy: 0.9948
Epoch 4/5
469/469 [==============================] - 2s 4ms/step - loss: 0.0126 - accuracy: 0.9964
Epoch 5/5
469/469 [==============================] - 2s 4ms/step - loss: 0.0102 - accuracy: 0.9971


Two quantities are being displayed during training: the "loss" of the network over the training data, and the accuracy of the network over 
the training data.

We quickly reach an accuracy of 0.989 (i.e. 98.9%) on the training data. Now let's check that our model performs well on the test set too:

In [27]:
test_loss, test_acc = network.evaluate(test_images, test_labels)
#1w张扔到神经网络，康康结果

313/313 [==============================] - 0s 719us/step - loss: 0.0678 - accuracy: 0.9817


In [30]:
print('test_acc:', test_acc) #test_acc正确率 旧考题全背下来，test题的正确率有误差，说明训练过头（泛化性）

test_acc: 0.9817000031471252


泛化能力（generalization ability）是指机器学习算法对新鲜样本的适应能力。 学习的目的是学到隐含在数据背后的规律，对具有同一规律的学习集以外的数据，经过训练的网络也能给出合适的输出，该能力称为泛化能力。


Our test set accuracy turns out to be 97.8% -- that's quite a bit lower than the training set accuracy. 
This gap between training accuracy and test accuracy is an example of "overfitting", 
the fact that machine learning models tend to perform worse on new data than on their training data. 
Overfitting will be a central topic in chapter 3.

This concludes our very first example -- you just saw how we could build and a train a neural network to classify handwritten digits, in 
less than 20 lines of Python code. In the next chapter, we will go in detail over every moving piece we just previewed, and clarify what is really 
going on behind the scenes. You will learn about "tensors", the data-storing objects going into the network, about tensor operations, which 
layers are made of, and about gradient descent, which allows our network to learn from its training examples.